services:
  streamlit:
    build: .
    container_name: superstore-streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    working_dir: /app
    command: streamlit run app/dashboard.py
